### PR TITLE
Add functions for encrypting and decrypting junipter $9$ type passwords

### PR DESCRIPTION
**Pull request by johanek**

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
@johanek can you provide the cli showing that this works as expected? It would be great to show doing the same thing as the test shows as well. On our side we will try and do the same.

**Comment by johanek** [comment]
> @johanek can you provide the cli showing that this works as expected? It would be great to show doing the same thing as the test shows as well. On our side we will try and do the same.

@itdependsnetworks hey, I'm sorry but I'm not clear what you're asking for. Here's an example of using the functions:

```
In [1]: from netutils.password import decrypt_juniper, encrypt_juniper

In [3]: encrypt_juniper('mypassword')
Out[3]: '$9$U/jqf9A0OIciku1hcMWjHqfz6CtOEhr'

In [4]: decrypt_juniper('$9$U/jqf9A0OIciku1hcMWjHqfz6CtOEhr')
Out[4]: 'mypassword'
```

The usage with examples is already in the docstrings for the function. Was there something else you were after?

**Comment by itdependsnetworks** [comment]
Sorry, just looking for the cli output on the junos side. We had it before (may have even been me :) ) where it didn't actually match what the vendor was doing.

**Comment by johanek** [comment]
```
# set system radius-server 10.0.0.1 secret RadiusSecret

# show | compare
[edit system radius-server]
+   10.0.0.1 secret "$9$vqY8NVws4GUHX7kPQzAtW8X7-wg4ZDHmX7Hm"; ## SECRET-DATA
```

```
In [1]: from netutils.password import decrypt_juniper, encrypt_juniper

In [2]: decrypt_juniper('$9$vqY8NVws4GUHX7kPQzAtW8X7-wg4ZDHmX7Hm')
Out[2]: 'RadiusSecret'
```

**Review by itdependsnetworks — APPROVED** [review]

**Comment by abates** [comment]
Please resolve merge conflicts and we can approve.

Thanks!

**Comment by johanek** [comment]
> @johanek Please resolve merge conflicts and we can approve.
> 
> Thanks!

Done!

**Review by abates — APPROVED** [review]

**Pull request merged**
