### PR TITLE
Fix for ASN functions

### PR DESCRIPTION
**Pull request by mzbroch**
Use proper names with regards to RFC :

```

   asplain
      refers to a syntax scheme of representing all AS numbers using
      decimal integer notation.  Using asplain notation, an AS number of
      value 65526 would be represented as the string "65526" and an AS
      number of value 65546 would be represented as the string "65546".

   asdot+
      refers to a syntax scheme of representing all AS numbers using a
      notation of two integer values joined by a period character: <high
      order 16-bit value in decimal>.<low order 16-bit value in
      decimal>.  Using asdot+ notation, an AS number of value 65526
      would be represented as the string "0.65526" and an AS number of
      value 65546 would be represented as the string "1.10".

   asdot
      refers to a syntax scheme of representing AS number values less
      than 65536 using asplain notation and representing AS number
      values equal to or greater than 65536 using asdot+ notation.
      Using asdot notation, an AS number of value 65526 would be
      represented as the string "65526" and an AS number of value 65546
      would be represented as the string "1.10".
```

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
We would have to deprecate, and wait until 2.0 to release.

**Comment by itdependsnetworks** [comment]
wait, nvm, this hasn't been released yet.

**Comment by jeffkala** [comment]
Validated only `asn_to_int` was the only function released so far. So we should be good.

**Comment by jeffkala** [comment]
Also get pytest passing.

**Comment by qduk** [comment]
@mzbroch Can you revert the table formatting? While it does objectively look better, we believe that's causing the failed test.

**Review by itdependsnetworks — APPROVED** [review]

**Pull request merged**
