### PR TITLE
Mikrotik Compliance Parser

### PR DESCRIPTION
**Pull request by nniehoff**
This PR adds a routeros parser.

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
Can you drop some tests here: https://github.com/networktocode/netutils/tree/develop/tests/unit/mock/config/compliance/compliance and here https://github.com/networktocode/netutils/tree/develop/tests/unit/mock/config/parser

They are just mock/expected type tests so should be pretty straight forward.

**Comment by jeffkala** [comment]
@nniehoff see Kens comment about tests.

**Comment by jeffkala** [comment]
bump @nniehoff

**Comment by itdependsnetworks** [comment]
Hey, going to close for now, feel free to open up once updated

**Pull request closed without merging**
